# Data Understanding

In [72]:
import warnings
warnings.filterwarnings("ignore")

In [73]:
import pandas as pd
df = pd.read_csv("../dataset/synthetic_patient_call_routing_dataset.csv")
df.head()

,Call_ID,Call_Timestamp,Patient_Age,Patient_Gender,State,Language,New_or_Existing_Patient,Call_Channel,Caller_Relationship,Chief_Complaint,Symptoms_Reported,Symptom_Severity,Duration_of_Symptoms_Days,Pain_Score,Emergency_Flag,Chronic_Condition,Insurance_Type,Preferred_Appointment_Urgency,Prior_Hospital_Visit_30D,Call_Duration_Minutes,Wait_Time_Minutes,Repeat_Caller,Sentiment,Call_Transcript_Summary,Recommended_Department
0,CALL-0000001,2025-02-27 20:09:18,33,Female,Alaska,English,Existing,Phone,Self,Needs to see a doctor and agent every,mild fever; blood pressure follow-up; general checkup request,High,10,9,No,Hypertension,Medicaid,Immediate,Yes,17,1,No,Anxious,"Caller reached the hospital call center general medical issue about mild fever, blood pressure follow-up, general checkup request, seeking immediate help, with a anxious tone, as an existing patient, with history of hypertension, cause bill scientist nation and required next-step guidance from primary care.",Primary Care
1,CALL-0000002,2025-06-27 20:33:38,27,Male,Louisiana,English,Existing,Phone,Self,"Caller reports abdominal pain, vomiting",abdominal pain; vomiting; acid reflux,Low,21,6,No,NaN,Private,Routine,No,9,5,No,Calm,"Family member called the access center stomach-related issue about abdominal pain, vomiting, acid reflux, seeking routine help, with a calm tone, as an existing patient, night respond with recommendation for gastroenterology.",Gastroenterology
2,CALL-0000003,2026-01-09 06:34:10,38,Male,Arizona,English,New,Phone,Caregiver,"Caller reports needs specialist slot, book appointment",needs specialist slot; book appointment,Medium,14,3,No,NaN,Private,Routine,No,11,3,No,Anxious,"Caller reached the hospital call center appointment request about needs specialist slot, book appointment, seeking routine help, with a anxious tone, recently future choice whatever with recommendation for scheduling.",Scheduling
3,CALL-0000004,2025-09-01 10:33:37,7,Female,Connecticut,English,Existing,Phone,Parent,"Patient is dealing with skin lesion, acne flare",skin lesion; acne flare,Low,93,1,No,Multiple,Medicaid,Soon,No,25,9,No,Distressed,"Family member called the access center dermatology-related issue about skin lesion, acne flare, seeking soon help, with a distressed tone, as an existing patient, with history of multiple, southern role movie win her need with recommendation for dermatology.",Dermatology
4,CALL-0000005,2024-10-07 16:00:57,17,Male,Iowa,English,Existing,Phone,Self,"Parent says child has fatigue, weight loss",fatigue; weight loss,Medium,83,3,No,Multiple,Private,Soon,Yes,12,9,No,Distressed,"Family member called the access center oncology follow-up about fatigue, weight loss, seeking soon help, with a distressed tone, as an existing patient, with history of multiple, significant world talk term herself law and required next-step guidance from pediatrics.",Pediatrics

In [74]:
df.shape

(10000, 25)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Call_ID                        10000 non-null  object
 1   Call_Timestamp                 10000 non-null  object
 2   Patient_Age                    10000 non-null  int64
 3   Patient_Gender                 10000 non-null  object
 4   State                          10000 non-null  object
 5   Language                       10000 non-null  object
 6   New_or_Existing_Patient        10000 non-null  object
 7   Call_Channel                   10000 non-null  object
 8   Caller_Relationship            10000 non-null  object
 9   Chief_Complaint                10000 non-null  object
 10  Symptoms_Reported              10000 non-null  object
 11  Symptom_Severity               10000 non-null  object
 12  Duration_of_Symptoms_Days      10000 non-null  int64
 13  Pain_Score                     10000 non-null  int64
 14  Emergency_Flag                 10000 non-null  object
 15  Chronic_Condition              5806 non-null   object
 16  Insurance_Type                 10000 non-null  object
 17  Preferred_Appointment_Urgency  10000 non-null  object
 18  Prior_Hospital_Visit_30D       10000 non-null  object
 19  Call_Duration_Minutes          10000 non-null  int64
 20  Wait_Time_Minutes              10000 non-null  int64
 21  Repeat_Caller                  10000 non-null  object
 22  Sentiment                      10000 non-null  object
 23  Call_Transcript_Summary        10000 non-null  object
 24  Recommended_Department         10000 non-null  object
dtypes: int64(5), object(20)
memory usage: 1.9+ MB

In [76]:
df.columns.tolist()

['Call_ID',
 'Call_Timestamp',
 'Patient_Age',
 'Patient_Gender',
 'State',
 'Language',
 'New_or_Existing_Patient',
 'Call_Channel',
 'Caller_Relationship',
 'Chief_Complaint',
 'Symptoms_Reported',
 'Symptom_Severity',
 'Duration_of_Symptoms_Days',
 'Pain_Score',
 'Emergency_Flag',
 'Chronic_Condition',
 'Insurance_Type',
 'Preferred_Appointment_Urgency',
 'Prior_Hospital_Visit_30D',
 'Call_Duration_Minutes',
 'Wait_Time_Minutes',
 'Repeat_Caller',
 'Sentiment',
 'Call_Transcript_Summary',
 'Recommended_Department']

In [77]:
df.dtypes

Call_ID                          object
Call_Timestamp                   object
Patient_Age                       int64
Patient_Gender                   object
State                            object
Language                         object
New_or_Existing_Patient          object
Call_Channel                     object
Caller_Relationship              object
Chief_Complaint                  object
Symptoms_Reported                object
Symptom_Severity                 object
Duration_of_Symptoms_Days         int64
Pain_Score                        int64
Emergency_Flag                   object
Chronic_Condition                object
Insurance_Type                   object
Preferred_Appointment_Urgency    object
Prior_Hospital_Visit_30D         object
Call_Duration_Minutes             int64
Wait_Time_Minutes                 int64
Repeat_Caller                    object
Sentiment                        object
Call_Transcript_Summary          object
Recommended_Department           object
dtype: object

In [78]:
df.describe()

,Patient_Age,Duration_of_Symptoms_Days,Pain_Score,Call_Duration_Minutes,Wait_Time_Minutes
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,43.093500,29.135200,4.478800,15.175000,7.852800
std,22.646873,36.973461,2.801167,8.774615,5.806006
min,0.000000,0.000000,0.000000,2.000000,0.000000
25%,26.000000,5.000000,2.000000,9.000000,3.000000
50%,41.000000,13.000000,5.000000,14.000000,7.000000
75%,59.000000,42.000000,7.000000,20.000000,13.000000
max,95.000000,180.000000,10.000000,45.000000,20.000000

In [79]:
df.describe(include="object")

,Call_ID,Call_Timestamp,Patient_Gender,State,Language,New_or_Existing_Patient,Call_Channel,Caller_Relationship,Chief_Complaint,Symptoms_Reported,Symptom_Severity,Emergency_Flag,Chronic_Condition,Insurance_Type,Preferred_Appointment_Urgency,Prior_Hospital_Visit_30D,Repeat_Caller,Sentiment,Call_Transcript_Summary,Recommended_Department
count,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000,5806,10000,10000,10000,10000,10000,10000,10000
unique,10000,9999,3,50,3,2,3,4,4260,2048,4,2,5,4,4,2,2,4,10000,17
top,CALL-0000001,2025-06-09 09:42:58,Female,Kansas,English,Existing,Phone,Self,Concern about mild symptoms,fatigue,Medium,No,Hypertension,Private,Soon,No,No,Calm,"Caller reached the hospital call center general medical issue about mild fever, blood pressure follow-up, general checkup request, seeking immediate help, with a anxious tone, as an existing patient, with history of hypertension, cause bill scientist nation and required next-step guidance from primary care.",Emergency Department
freq,1,2,4956,238,7771,7222,7619,7216,74,110,3895,8571,1741,5380,3052,7134,7218,3598,1,1514

# Feature Summary

In [80]:
feature_summary = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Unique Values": df.nunique(),
    "Duplicated Rows": df.duplicated().sum(),
    "Memory Usage (MB)": round(df.memory_usage(deep=True)/1024**2, 2), 
})

feature_summary

,Data Type,Missing Values,Unique Values,Duplicated Rows,Memory Usage (MB)
Call_Channel,object,0.0,3.0,0,0.61
Call_Duration_Minutes,int64,0.0,44.0,0,0.08
Call_ID,object,0.0,10000.0,0,0.66
Call_Timestamp,object,0.0,9999.0,0,0.72
Call_Transcript_Summary,object,0.0,10000.0,0,2.89
Caller_Relationship,object,0.0,4.0,0,0.59
Chief_Complaint,object,0.0,4260.0,0,0.96
Chronic_Condition,object,4194.0,5.0,0,0.50
Duration_of_Symptoms_Days,int64,0.0,181.0,0,0.08
Emergency_Flag,object,0.0,2.0,0,0.56
Index,NaN,NaN,NaN,0,0.00
Insurance_Type,object,0.0,4.0,0,0.61
Language,object,0.0,3.0,0,0.61
New_or_Existing_Patient,object,0.0,2.0,0,0.61
Pain_Score,int64,0.0,11.0,0,0.08
Patient_Age,int64,0.0,96.0,0,0.08
Patient_Gender,object,0.0,3.0,0,0.59
Preferred_Appointment_Urgency,object,0.0,4.0,0,0.61
Prior_Hospital_Visit_30D,object,0.0,2.0,0,0.57
Recommended_Department,object,0.0,17.0,0,0.66
Repeat_Caller,object,0.0,2.0,0,0.57
Sentiment,object,0.0,4.0,0,0.61
State,object,0.0,50.0,0,0.62
Symptom_Severity,object,0.0,4.0,0,0.59
Symptoms_Reported,object,0.0,2048.0,0,0.82
Wait_Time_Minutes,int64,0.0,21.0,0,0.08

## Data Cleaning

In [81]:
# Drop Unnecessary Columns
df.drop(columns=["Call_ID"], inplace=True)

In [82]:
# Handle Missing Values
df["Chronic_Condition"] = df["Chronic_Condition"].fillna("No Chronic Condition")
df.isnull().sum()

Call_Timestamp                   0
Patient_Age                      0
Patient_Gender                   0
State                            0
Language                         0
New_or_Existing_Patient          0
Call_Channel                     0
Caller_Relationship              0
Chief_Complaint                  0
Symptoms_Reported                0
Symptom_Severity                 0
Duration_of_Symptoms_Days        0
Pain_Score                       0
Emergency_Flag                   0
Chronic_Condition                0
Insurance_Type                   0
Preferred_Appointment_Urgency    0
Prior_Hospital_Visit_30D         0
Call_Duration_Minutes            0
Wait_Time_Minutes                0
Repeat_Caller                    0
Sentiment                        0
Call_Transcript_Summary          0
Recommended_Department           0
dtype: int64

In [83]:
print("Shape of the dataset after handling missing values:", df.shape)
df.head()

Shape of the dataset after handling missing values: (10000, 24)

,Call_Timestamp,Patient_Age,Patient_Gender,State,Language,New_or_Existing_Patient,Call_Channel,Caller_Relationship,Chief_Complaint,Symptoms_Reported,Symptom_Severity,Duration_of_Symptoms_Days,Pain_Score,Emergency_Flag,Chronic_Condition,Insurance_Type,Preferred_Appointment_Urgency,Prior_Hospital_Visit_30D,Call_Duration_Minutes,Wait_Time_Minutes,Repeat_Caller,Sentiment,Call_Transcript_Summary,Recommended_Department
0,2025-02-27 20:09:18,33,Female,Alaska,English,Existing,Phone,Self,Needs to see a doctor and agent every,mild fever; blood pressure follow-up; general checkup request,High,10,9,No,Hypertension,Medicaid,Immediate,Yes,17,1,No,Anxious,"Caller reached the hospital call center general medical issue about mild fever, blood pressure follow-up, general checkup request, seeking immediate help, with a anxious tone, as an existing patient, with history of hypertension, cause bill scientist nation and required next-step guidance from primary care.",Primary Care
1,2025-06-27 20:33:38,27,Male,Louisiana,English,Existing,Phone,Self,"Caller reports abdominal pain, vomiting",abdominal pain; vomiting; acid reflux,Low,21,6,No,No Chronic Condition,Private,Routine,No,9,5,No,Calm,"Family member called the access center stomach-related issue about abdominal pain, vomiting, acid reflux, seeking routine help, with a calm tone, as an existing patient, night respond with recommendation for gastroenterology.",Gastroenterology
2,2026-01-09 06:34:10,38,Male,Arizona,English,New,Phone,Caregiver,"Caller reports needs specialist slot, book appointment",needs specialist slot; book appointment,Medium,14,3,No,No Chronic Condition,Private,Routine,No,11,3,No,Anxious,"Caller reached the hospital call center appointment request about needs specialist slot, book appointment, seeking routine help, with a anxious tone, recently future choice whatever with recommendation for scheduling.",Scheduling
3,2025-09-01 10:33:37,7,Female,Connecticut,English,Existing,Phone,Parent,"Patient is dealing with skin lesion, acne flare",skin lesion; acne flare,Low,93,1,No,Multiple,Medicaid,Soon,No,25,9,No,Distressed,"Family member called the access center dermatology-related issue about skin lesion, acne flare, seeking soon help, with a distressed tone, as an existing patient, with history of multiple, southern role movie win her need with recommendation for dermatology.",Dermatology
4,2024-10-07 16:00:57,17,Male,Iowa,English,Existing,Phone,Self,"Parent says child has fatigue, weight loss",fatigue; weight loss,Medium,83,3,No,Multiple,Private,Soon,Yes,12,9,No,Distressed,"Family member called the access center oncology follow-up about fatigue, weight loss, seeking soon help, with a distressed tone, as an existing patient, with history of multiple, significant world talk term herself law and required next-step guidance from pediatrics.",Pediatrics

# Save Clean Dataset

In [84]:
df.to_csv("../dataset/cleaned_data.csv", index=False)
print("Cleaned dataset saved to 'cleaned_data.csv'")

Cleaned dataset saved to 'cleaned_data.csv'

# Conclusion

The data understanding and data cleaning phase was completed successfully.

The following tasks were performed during this notebook:

- Loaded and inspected the dataset.
- Examined the dataset structure, dimensions, and data types.
- Identified missing values and duplicate records.
- Analyzed unique values for each feature.
- Understood the purpose of every feature.
- Identified the target variable (**Recommended_Department**).
- Identified the primary NLP feature (**Chief_Complaint**).
- Removed the unnecessary **Call_ID** feature.
- Handled missing values in the **Chronic_Condition** feature.
- Saved the cleaned dataset for further analysis.

The cleaned dataset is now ready for Exploratory Data Analysis (EDA), where visualizations and business insights will be generated before moving to feature engineering and machine learning.